name: humanizer
description: A library to convert Dart values into human-friendly representations.
version: 2.3.0
repository: https://github.com/kentcb/humanizer

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  decimal: ^3.0.2
  intl: ^0.19.0
  meta: ^1.15.0
  rational: ^2.2.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.1
